name: circle_bricks_breaker
description: A bricks breaker game made with Flutter.

version: 0.0.1+1

environment:
  sdk: ">=3.1.5 <4.0.0"

dependencies:
  equatable: ^2.0.5
  flame: ^1.14.0
  flame_bloc: ^1.10.9
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3

dev_dependencies:
  flame_lint: ^1.1.2
  flutter_test:
    sdk: flutter

  lint: ^2.3.0

flutter:
  uses-material-design: true
